name: Website Deployment Reusable Workflow
on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name of the artifact to download'
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
